DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS (  
CUSTOMER_NAME VARCHAR(50) PRIMARY KEY,
ORDER_DATE VARCHAR(10) NOT NULL,  
SHIPPING_ADDRESS VARCHAR(50) NOT NULL,  
ORDER_ID INT(50) NOT NULL,  
TOTAL DOUBLE(20) NOT NULL
);